### ISSUE TITLE
[REQ] Tidal-Media-Downloader

### ISSUE THREAD

**Issue by forart** [shirooo39/MiXLab#23]
> an application that lets you download videos and tracks from Tidal
by @yaronzz

git: https://github.com/yaronzz/Tidal-Media-Downloader

Hope that inspires !

**Comment by AndreVuillemot160** [comment]
@forart I think it will be better to use streamrip project https://github.com/nathom/streamrip

**Comment by forart** [comment]
@AndreVuillemot160 Totally agree, would be great.

**Comment by shirooo39** [comment]
Sorry for bringing the bad news but this is what I got
```Python
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 5, in <module>
    from streamrip.cli import main
  File "/usr/local/lib/python3.7/dist-packages/streamrip/cli.py", line 11, in <module>
    from .core import MusicDL
  File "/usr/local/lib/python3.7/dist-packages/streamrip/core.py", line 22, in <module>
    from .downloader import Album, Artist, Label, Playlist, Track
  File "/usr/local/lib/python3.7/dist-packages/streamrip/downloader.py", line 112
    if (u := kwargs.get("cover_url")) is not None:
          ^
SyntaxError: invalid syntax
```

streamrip requires Python >= 3.8 while the pre-installed Python in Google Colab is 3.7
> First, ensure Python (version 3.8 or greater)

**Comment by forart** [comment]
Ouch!

Could Chimera help, then ?

https://github.com/KGTasa/chimera

**Comment by soulspark666** [comment]
![image](https://user-images.githubusercontent.com/37495396/145194020-4b6af59c-e603-4ed2-bd8a-8c9c3d117ad7.png)
Was able to get 3.10 easily
https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/

**Comment by soulspark666** [comment]
![image](https://user-images.githubusercontent.com/37495396/145196391-bb7b17b7-3602-42e9-9d5b-790504ba74b1.png)
Was able to get 3.8.12
https://www.itsupportwale.com/blog/how-to-upgrade-to-python-3-8-on-ubuntu-18-04-lts/

**Comment by soulspark666** [comment]
![image](https://user-images.githubusercontent.com/37495396/145197188-1d69424f-e0a6-4662-9c7b-61fe63c9ce5d.png)
did not deep for now but got this, hope someone can help

**Comment by AndreVuillemot160** [comment]
My friend made this https://github.com/taskylizard/uwustreamrip/blob/main/uwustreamrip.ipynb

It works tho.

**Comment by shirooo39** [comment]
> My friend made this https://github.com/taskylizard/uwustreamrip/blob/main/uwustreamrip.ipynb
> 
> It works tho.

This works?
instead of re-inventing the wheel, what if I just copy that notebook and paste it into mine? what do you guys think?

**Comment by forart** [comment]
@shirooo39 I don't have a Tidal/Quobuz/etc. account, but seems to work.

Yes, reinventing the wheel is not good, but a better "GUI" could be interesting.

**Comment by taskylizard** [comment]
> This works? instead of re-inventing the wheel, what if I just copy that notebook and paste it into mine? what do you guys think?

I don't have any problems with that, as for collaboration, sure.
